# Generated by Django 4.1.6 on 2023-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW', '0002_hashtag_product_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
